#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Proxit")]
	public partial class ProductDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ProductDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ProxitConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Producten> Productens
		{
			get
			{
				return this.GetTable<Producten>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producten")]
	public partial class Producten
	{
		
		private int _id;
		
		private string _productnaam;
		
		private string _btwtarief;
		
		private string _verkoopprijs;
		
		private string _garantietermijn;
		
		public Producten()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productnaam", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string productnaam
		{
			get
			{
				return this._productnaam;
			}
			set
			{
				if ((this._productnaam != value))
				{
					this._productnaam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_btwtarief", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string btwtarief
		{
			get
			{
				return this._btwtarief;
			}
			set
			{
				if ((this._btwtarief != value))
				{
					this._btwtarief = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verkoopprijs", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string verkoopprijs
		{
			get
			{
				return this._verkoopprijs;
			}
			set
			{
				if ((this._verkoopprijs != value))
				{
					this._verkoopprijs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_garantietermijn", DbType="NChar(10)")]
		public string garantietermijn
		{
			get
			{
				return this._garantietermijn;
			}
			set
			{
				if ((this._garantietermijn != value))
				{
					this._garantietermijn = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
