#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Proxit")]
	public partial class TicketDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKlanten(Klanten instance);
    partial void UpdateKlanten(Klanten instance);
    partial void DeleteKlanten(Klanten instance);
    partial void InsertTicket(Ticket instance);
    partial void UpdateTicket(Ticket instance);
    partial void DeleteTicket(Ticket instance);
    #endregion
		
		public TicketDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ProxitConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TicketDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicketDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicketDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicketDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Klanten> Klantens
		{
			get
			{
				return this.GetTable<Klanten>();
			}
		}
		
		public System.Data.Linq.Table<Ticket> Tickets
		{
			get
			{
				return this.GetTable<Ticket>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klanten")]
	public partial class Klanten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _voornaam;
		
		private string _achternaam;
		
		private string _bedrijf;
		
		private string _straat;
		
		private string _nummer;
		
		private string _postcode;
		
		private string _gemeente;
		
		private string _land;
		
		private string _telefoonnummer;
		
		private string _email;
		
		private EntitySet<Ticket> _Tickets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnvoornaamChanging(string value);
    partial void OnvoornaamChanged();
    partial void OnachternaamChanging(string value);
    partial void OnachternaamChanged();
    partial void OnbedrijfChanging(string value);
    partial void OnbedrijfChanged();
    partial void OnstraatChanging(string value);
    partial void OnstraatChanged();
    partial void OnnummerChanging(string value);
    partial void OnnummerChanged();
    partial void OnpostcodeChanging(string value);
    partial void OnpostcodeChanged();
    partial void OngemeenteChanging(string value);
    partial void OngemeenteChanged();
    partial void OnlandChanging(string value);
    partial void OnlandChanged();
    partial void OntelefoonnummerChanging(string value);
    partial void OntelefoonnummerChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public Klanten()
		{
			this._Tickets = new EntitySet<Ticket>(new Action<Ticket>(this.attach_Tickets), new Action<Ticket>(this.detach_Tickets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voornaam", DbType="VarChar(100)")]
		public string voornaam
		{
			get
			{
				return this._voornaam;
			}
			set
			{
				if ((this._voornaam != value))
				{
					this.OnvoornaamChanging(value);
					this.SendPropertyChanging();
					this._voornaam = value;
					this.SendPropertyChanged("voornaam");
					this.OnvoornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_achternaam", DbType="VarChar(100)")]
		public string achternaam
		{
			get
			{
				return this._achternaam;
			}
			set
			{
				if ((this._achternaam != value))
				{
					this.OnachternaamChanging(value);
					this.SendPropertyChanging();
					this._achternaam = value;
					this.SendPropertyChanged("achternaam");
					this.OnachternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedrijf", DbType="VarChar(100)")]
		public string bedrijf
		{
			get
			{
				return this._bedrijf;
			}
			set
			{
				if ((this._bedrijf != value))
				{
					this.OnbedrijfChanging(value);
					this.SendPropertyChanging();
					this._bedrijf = value;
					this.SendPropertyChanged("bedrijf");
					this.OnbedrijfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_straat", DbType="VarChar(100)")]
		public string straat
		{
			get
			{
				return this._straat;
			}
			set
			{
				if ((this._straat != value))
				{
					this.OnstraatChanging(value);
					this.SendPropertyChanging();
					this._straat = value;
					this.SendPropertyChanged("straat");
					this.OnstraatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nummer", DbType="VarChar(5)")]
		public string nummer
		{
			get
			{
				return this._nummer;
			}
			set
			{
				if ((this._nummer != value))
				{
					this.OnnummerChanging(value);
					this.SendPropertyChanging();
					this._nummer = value;
					this.SendPropertyChanged("nummer");
					this.OnnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcode", DbType="VarChar(8)")]
		public string postcode
		{
			get
			{
				return this._postcode;
			}
			set
			{
				if ((this._postcode != value))
				{
					this.OnpostcodeChanging(value);
					this.SendPropertyChanging();
					this._postcode = value;
					this.SendPropertyChanged("postcode");
					this.OnpostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gemeente", DbType="VarChar(100)")]
		public string gemeente
		{
			get
			{
				return this._gemeente;
			}
			set
			{
				if ((this._gemeente != value))
				{
					this.OngemeenteChanging(value);
					this.SendPropertyChanging();
					this._gemeente = value;
					this.SendPropertyChanged("gemeente");
					this.OngemeenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_land", DbType="VarChar(50)")]
		public string land
		{
			get
			{
				return this._land;
			}
			set
			{
				if ((this._land != value))
				{
					this.OnlandChanging(value);
					this.SendPropertyChanging();
					this._land = value;
					this.SendPropertyChanged("land");
					this.OnlandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoonnummer", DbType="VarChar(15)")]
		public string telefoonnummer
		{
			get
			{
				return this._telefoonnummer;
			}
			set
			{
				if ((this._telefoonnummer != value))
				{
					this.OntelefoonnummerChanging(value);
					this.SendPropertyChanging();
					this._telefoonnummer = value;
					this.SendPropertyChanged("telefoonnummer");
					this.OntelefoonnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klanten_Ticket", Storage="_Tickets", ThisKey="id", OtherKey="klantid")]
		public EntitySet<Ticket> Tickets
		{
			get
			{
				return this._Tickets;
			}
			set
			{
				this._Tickets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tickets(Ticket entity)
		{
			this.SendPropertyChanging();
			entity.Klanten = this;
		}
		
		private void detach_Tickets(Ticket entity)
		{
			this.SendPropertyChanging();
			entity.Klanten = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tickets")]
	public partial class Ticket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _klantid;
		
		private string _gebruikerid;
		
		private System.Nullable<System.DateTime> _datetime;
		
		private System.Nullable<bool> _prioritair;
		
		private int _tickettype;
		
		private int _status;
		
		private EntityRef<Klanten> _Klanten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnklantidChanging(System.Nullable<int> value);
    partial void OnklantidChanged();
    partial void OngebruikeridChanging(string value);
    partial void OngebruikeridChanged();
    partial void OndatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OndatetimeChanged();
    partial void OnprioritairChanging(System.Nullable<bool> value);
    partial void OnprioritairChanged();
    partial void OntickettypeChanging(int value);
    partial void OntickettypeChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    #endregion
		
		public Ticket()
		{
			this._Klanten = default(EntityRef<Klanten>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_klantid", DbType="Int")]
		public System.Nullable<int> klantid
		{
			get
			{
				return this._klantid;
			}
			set
			{
				if ((this._klantid != value))
				{
					if (this._Klanten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnklantidChanging(value);
					this.SendPropertyChanging();
					this._klantid = value;
					this.SendPropertyChanged("klantid");
					this.OnklantidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gebruikerid", DbType="VarChar(MAX)")]
		public string gebruikerid
		{
			get
			{
				return this._gebruikerid;
			}
			set
			{
				if ((this._gebruikerid != value))
				{
					this.OngebruikeridChanging(value);
					this.SendPropertyChanging();
					this._gebruikerid = value;
					this.SendPropertyChanged("gebruikerid");
					this.OngebruikeridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datetime", DbType="DateTime2")]
		public System.Nullable<System.DateTime> datetime
		{
			get
			{
				return this._datetime;
			}
			set
			{
				if ((this._datetime != value))
				{
					this.OndatetimeChanging(value);
					this.SendPropertyChanging();
					this._datetime = value;
					this.SendPropertyChanged("datetime");
					this.OndatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prioritair", DbType="Bit")]
		public System.Nullable<bool> prioritair
		{
			get
			{
				return this._prioritair;
			}
			set
			{
				if ((this._prioritair != value))
				{
					this.OnprioritairChanging(value);
					this.SendPropertyChanging();
					this._prioritair = value;
					this.SendPropertyChanged("prioritair");
					this.OnprioritairChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tickettype", DbType="Int NOT NULL")]
		public int tickettype
		{
			get
			{
				return this._tickettype;
			}
			set
			{
				if ((this._tickettype != value))
				{
					this.OntickettypeChanging(value);
					this.SendPropertyChanging();
					this._tickettype = value;
					this.SendPropertyChanged("tickettype");
					this.OntickettypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klanten_Ticket", Storage="_Klanten", ThisKey="klantid", OtherKey="id", IsForeignKey=true)]
		public Klanten Klanten
		{
			get
			{
				return this._Klanten.Entity;
			}
			set
			{
				Klanten previousValue = this._Klanten.Entity;
				if (((previousValue != value) 
							|| (this._Klanten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klanten.Entity = null;
						previousValue.Tickets.Remove(this);
					}
					this._Klanten.Entity = value;
					if ((value != null))
					{
						value.Tickets.Add(this);
						this._klantid = value.id;
					}
					else
					{
						this._klantid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Klanten");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
